# Generated by Django 6.0.7 on 2026-09-17 12:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0005_alter_appointment_appointment_type'),
        ('insoles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(choices=[('consommable', 'Consommable'), ('matiere_premiere', 'Matière première'), ('autre', 'Autre')], default='consommable', max_length=20)),
                ('unit', models.CharField(default='unité', help_text='unité, boîte, m, paire, L…', max_length=20)),
                ('current_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('minimum_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('pack_size', models.DecimalField(decimal_places=3, default=1, max_digits=10)),
                ('supplier_name', models.CharField(blank=True, max_length=200)),
                ('supplier_lead_time_days', models.PositiveIntegerField(default=7)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_stock_items',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('livraison', 'Livraison fournisseur'), ('utilisation', 'Consommation (soin / fabrication)'), ('inventaire', "Comptage / correction d'inventaire"), ('ajustement', 'Ajustement manuel (casse, perte…)')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='appointments.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
                ('insole_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='insoles.insoleorder')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'inventory_stock_movements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsumptionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger', models.CharField(choices=[('bilan_podologique', 'Bilan podologique'), ('remise_semelles', 'Remise de semelles'), ('soin_pedicurie', 'Soin de pédicurie'), ('suivi_controle', 'Suivi / Contrôle'), ('insole_order', "Fabrication d'une paire de semelles")], max_length=30)),
                ('quantity_per_unit', models.DecimalField(decimal_places=3, max_digits=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_rules', to='inventory.stockitem')),
            ],
            options={
                'db_table': 'inventory_consumption_rules',
                'ordering': ['item__name'],
                'unique_together': {('item', 'trigger')},
            },
        ),
    ]
