# Generated by Django 6.0.7 on 2026-07-31 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointments', '0002_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsoleOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('empreinte_prise', "Examen effectué / Prise d'empreinte"), ('conception', 'En cours de conception / Modélisation'), ('usinage_assemblage', "En cours d'usinage / Assemblage"), ('pret_essayage', 'Prêt pour essayage'), ('livre', 'Livré au patient')], default='empreinte_prise', max_length=30)),
                ('materials_used', models.TextField(blank=True)),
                ('corrections', models.TextField(blank=True)),
                ('manufacturing_notes', models.TextField(blank=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appointments.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insole_orders', to='patients.patient')),
                ('practitioner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
            ],
            options={
                'db_table': 'insole_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsoleAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_path', models.TextField()),
                ('file_type', models.CharField(choices=[('photo_empreinte', 'Photo empreinte'), ('photo_pied', 'Photo pied'), ('scan_3d', 'Scan 3D'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
                ('insole_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='insoles.insoleorder')),
            ],
            options={
                'db_table': 'insole_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='InsoleStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('empreinte_prise', "Examen effectué / Prise d'empreinte"), ('conception', 'En cours de conception / Modélisation'), ('usinage_assemblage', "En cours d'usinage / Assemblage"), ('pret_essayage', 'Prêt pour essayage'), ('livre', 'Livré au patient')], max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile')),
                ('insole_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='insoles.insoleorder')),
            ],
            options={
                'verbose_name_plural': 'insole status histories',
                'db_table': 'insole_status_history',
                'ordering': ['changed_at'],
            },
        ),
    ]
