# Generated by Django 6.0.7 on 2026-07-31 11:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('appointment_type', models.CharField(choices=[('bilan_podologique', 'Bilan podologique'), ('remise_semelles', 'Remise de semelles'), ('soin_pedicurie', 'Soin de pédicurie'), ('suivi_controle', 'Suivi / Contrôle')], max_length=30)),
                ('status', models.CharField(choices=[('confirme', 'Confirmé'), ('en_attente', 'En attente'), ('annule', 'Annulé'), ('honore', 'Honoré')], default='en_attente', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['start_time'],
            },
        ),
    ]
