# Generated by Django 6.0.7 on 2026-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='odoo_event_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
