# Generated by Django 6.0.7 on 2026-09-13 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointment_odoo_event_id'),
        ('patients', '0002_patient_odoo_partner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='booked_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='patients.patient'),
        ),
    ]
