# Generated by Django 6.0.7 on 2026-09-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_booked_name_alter_appointment_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('bilan_podologique', 'Bilan podologique'), ('remise_semelles', 'Remise de semelles'), ('soin_pedicurie', 'Soin de pédicurie'), ('suivi_controle', 'Suivi / Contrôle'), ('absence', 'Absence / Congé')], max_length=30),
        ),
    ]
