# Generated by Django 6.0.7 on 2026-09-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='odoo_partner_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
